### ISSUE TITLE
build-ubuntu?

### ISSUE THREAD

**Issue by dcbartlett** [luisvasquez/cpuminer-easy#7]
https://github.com/luisvasquez/cpuminer-easy/blob/b124474796f2a07d9319d9d56d56a41939e97453/build-ubuntu.sh#L14

Should this say build-ubuntu?

**Comment by DanDawson** [comment]
If you change it to build-ubuntu it just keeps running itself in an endless loop.

**Comment by dcbartlett** [comment]
Yerah, i think was was half asleep....Ignore my derpness.
